from test_setup import setup_project_root
setup_project_root()

from rwg.rwg1 import *

filename_plate = 'data/antennas_mesh/plate.mat'
p, t = load_mesh_file(filename_plate)
points_plate = Points(p)
print(f"Taille tableau point = {points_plate.points.shape}")
print(f"On a {points_plate.total_of_points} points au total")
print("point = ")
print(points_plate.points)
triangles_plate = Triangles(t)
print(f"Taille tableau triangles = {triangles_plate.triangles.shape}")
print(f"On a {triangles_plate.total_of_triangles} triangle au total")
print("triangle =")
print(triangles_plate.triangles)
triangles_plate.filter_triangles()
print(f"On a {triangles_plate.total_of_triangles} triangle au total")
triangles_plate.calculate_triangles_area_and_center(points_plate)
print(f"Taille tableau Aire triangle = {triangles_plate.triangles_area.shape}")
print("Aire des triangles =")
print(triangles_plate.triangles_area)
print(f"Taille tableau centre triangle = {triangles_plate.triangles_center.shape}")
print("Centre des triangles =")
print(triangles_plate.triangles_center)
edges_plate = triangles_plate.get_edges()
print(f"triangle Plus shape = {triangles_plate.triangles_plus.shape}")
print("triangle Plus =")
print(triangles_plate.triangles_plus)
print(f"triangle Minus = {triangles_plate.triangles_minus.shape}")
print("triangle Minus =")
print(triangles_plate.triangles_minus)
print("Edge first point list =")
print(edges_plate.first_points)
print("Edge second point list =")
print(edges_plate.second_points)
print(f"Total number of edge = {edges_plate.total_number_of_edges}")
edges_plate.compute_edges_length(points_plate)
print("Edge length list =")
print(edges_plate.edges_length)
filter_complexes_jonctions(points_plate, triangles_plate, edges_plate)
# Sauvegarde des données
save_folder_name = 'data/antennas_mesh1/'
DataManager_rwg1.save_data(filename_plate, save_folder_name, points_plate, triangles_plate, edges_plate)